export const API_ENDPOINTS = {
  AUTH: "/api/auth",
  PRODUCTS: "/api/products",
  PRODUCT: (id: string) => `/api/products/${id}`,
  CATEGORIES: "/api/categories",
  CATEGORY: (id: string) => `/api/categories/${id}`,
  ORDERS: "/api/orders",
  ORDER: (id: string) => `/api/orders/${id}`,
  REVIEWS: "/api/reviews",
  REVIEW: (id: string) => `/api/reviews/${id}`,
  PAYMENT_CASHFREE: "/api/payment/cashfree",
  PAYMENT_VERIFY: "/api/payment/cashfree/verify",
  WEBHOOK_CASHFREE: "/api/webhooks/cashfree",
  EMAIL: "/api/email",
  CART: "/api/cart",
  USERS: "/api/users",
  USER: (id: string) => `/api/users/${id}`,
  USER_ROLE: (id: string) => `/api/users/${id}/role`,
  WISHLIST: "/api/wishlist",
  UPLOAD: "/api/upload",
  COUNTRY_CALLING_CODES:
    "https://countriesnow.space/api/v0.1/countries/codes",
} as const;
