export const API_ENDPOINTS = {
  AUTH: "/api/auth",
  AUTH_FORGOT_PASSWORD: "/api/auth/forgot-password",
  PRODUCTS: "/api/products",
  PRODUCT: (id: string) => `/api/products/${id}`,
  CATEGORIES: "/api/categories",
  CATEGORY: (id: string) => `/api/categories/${id}`,
  ORDERS: "/api/orders",
  ORDER: (id: string) => `/api/orders/${id}`,
  ORDER_CUSTOMIZATION: (id: string) => `/api/orders/${id}/customization`,
  ORDER_TRACK: (id: string) => `/api/orders/${id}/track`,
  REVIEWS: "/api/reviews",
  REVIEW: (id: string) => `/api/reviews/${id}`,
  PAYMENT_CASHFREE: "/api/payment/cashfree",
  PAYMENT_VERIFY: "/api/payment/cashfree/verify",
  WEBHOOK_CASHFREE: "/api/webhooks/cashfree",
  WEBHOOK_DELIVERY_UPDATES: "/api/webhooks/delivery-updates",
  EMAIL: "/api/email",
  CART: "/api/cart",
  USERS: "/api/users",
  USER: (id: string) => `/api/users/${id}`,
  USER_ROLE: (id: string) => `/api/users/${id}/role`,
  PROFILE_ADDRESSES: "/api/profile/addresses",
  UPLOAD: "/api/upload",
  ADMIN_ANALYTICS: "/api/admin/analytics",
  ORDER_SYNC_SHIPMENT: (id: string) => `/api/admin/orders/${id}/sync-shipment`,
  SHIPPING_DELIVERY_ESTIMATE: "/api/shipping/delivery-estimate",
  COUNTRY_CALLING_CODES:
    "https://countriesnow.space/api/v0.1/countries/codes",
} as const;
